version: "3.7"
services:
  frontEnd:
    image: appfrontend:miniproject
    ports:
    - published: 5000
      target: 5000
    deploy:
      replicas: 1
  backEnd:
    image: appbackend:miniproject
    ports:
    - published: 5001
      target: 5001
    deploy:
      replicas: 1