version: "3.7"
services:
  frontEnd:
    image: appfrontend:miniproject
    ports:
    - target: 5000
    deploy:
      replicas: 1
  backEnd:
    image: appbackend:miniproject
    ports:
    - target: 5001
    deploy:
      replicas: 1