version: "3.7"
services:
  frontEnd:
    image: thomashennessy/appfrontend:miniproject
    ports:
    - target: 5000
    deploy:
      replicas: 1
  backEnd:
    image: thomashennessy/appbackend:miniproject
    ports:
    - target: 5001
    deploy:
      replicas: 1
  nginx:
    image: nginx:latest
    ports:
    - published: 80
      target: 80
    depends_on:
    - frontEnd
      backEnd
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf